kind: pipeline
type: docker
name: Backend

steps:
  - name: prepare package
    image: python:3.8
    commands:
      - cd app
      - pip install poetry
      - poetry export -f requirements.txt > requirements.txt
      - pip install -r requirements.txt -t .
      - chmod -R 755 .
    depends_on:
      - clone

  - name: zip app
    image: requinard2/base
    commands:
      - cd app
      - zip -r ../app.zip -7 .
    depends_on:
      - prepare package

  - name: build frontend
    image: requinard2/node
    commands:
      - cd frontend
      - npm ci
      - npm run build

  - name: terraform init
    image: requinard2/terraform
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret
    commands:
      - cd terraform
      - terraform init
    depends_on:
      - clone

  - name: switch workspace
    image: requinard2/terraform
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret
    commands:
      - cd terraform
      - terraform workspace select ${DRONE_COMMIT_BRANCH} || terraform workspace new ${DRONE_COMMIT_BRANCH}
    depends_on:
      - terraform init

  - name: terraform apply
    image: requinard2/terraform
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret
    commands:
      - cd terraform
      - terraform apply -auto-approve
    depends_on:
      - zip app
      - terraform init
      - switch workspace
      - build frontend
